server:
  port: 8084

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: satish
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

razorpay:
  key: rzp_test_Ssn4eIKgveB1vK
  secret: eOn2BV0eYyuPinL3xsdcK570

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always
